### ISSUE TITLE
Levels recoding not working

### ISSUE THREAD

**Issue by bassam-abulnoor** [juba/questionr#131] opened 2022-01-21 09:30 UTC
After 0.7.6 update levels recoding function not working giving the error message "%>% unexpected character". When I rolled back to earlier version it returned back to normal. I really like your package and think it's super useful thanks.

**Comment by juba** [comment] 2022-01-21 10:13
Thanks !

You're talking about the levels recoding addin, right ?

I can't seem to reproduce your issue right now. Do you load the `tidyverse` or `forcats` package before calling the addin ? Could you describe when the error message appears exactly ?

**Comment by bassam-abulnoor** [comment] 2022-01-21 17:57
Thanks for your comment. Yes exactly I'm talking about the addin and the error occurs in the final step of code production and tidyverse is loaded before that. I'm attaching a photo with the error hope it helps.
![image](https://user-images.githubusercontent.com/51817217/150576671-62e7c33a-51db-4653-ad5e-8758f5ca6a74.png)

**Comment by juba** [comment] 2022-01-22 17:07
Oh, I see ! You were trying to recode a numeric variable I guess ? There was an error in the generated `forcats` recoding code in this case.

Could you please install the latest development version to see if the issue is fixed for you ?

```r
remotes::install_github("juba/questionr")
```

Thanks for taking the time to report the issue and to provide details allowing me to fix it (I hope !).

**Comment by bassam-abulnoor** [comment] 2022-01-22 17:26
Yes it's fixed! thanks a lot for your efforts and fast response. A different issue I encountered now that may be related but this time with the factors ordering addin. If you try to order a numeric variable the code works but an error is displayed in the check panel don't know if this is intentional or not thought it might be helpful to report.   
![A](https://user-images.githubusercontent.com/51817217/150649028-a24019c4-5ef8-45f8-939a-d3503829d4cb.png)
Can't thank you enough for this package it's literally a life saver. My most used r package after tidyverse and I'm very glad that I finally have the chance ti thank you.

**Comment by juba** [comment] 2022-01-23 12:27
Thanks for the kind words !

You're right, there was also an error when reordering a numeric variable with `forcats`, I didn't test this use case. This should be fixed now in the development version, thanks again for reporting the issue.

I'll close this issue for now, but don't hesitate to reopen it if needed.

**Closed by juba** 2022-01-23 12:27 UTC

**Comment by bassam-abulnoor** [comment] 2022-01-23 13:12
Thanks again :)
